name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: [ "main" ]
    paths:
      - "db/**"
  workflow_dispatch: {}

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest
    # Definimos las variables a nivel de JOB para que todos los pasos las vean
    env:
      ECR_REGISTRY: 271179226854.dkr.ecr.us-east-1.amazonaws.com
      IMAGE_NAME: tienda-db

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y Empujar imagen
      run: |
        # Verificación de seguridad
        if [ -z "$ECR_REGISTRY" ]; then
          echo "Error: ECR_REGISTRY no esta definido."
          exit 1
        fi
        
        cd db
        docker build -t $IMAGE_NAME .
        
        # Etiquetar y subir usando la variable del job
        docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest
        docker push $ECR_REGISTRY/$IMAGE_NAME:latest

    - name: Desplegar DB vía SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_DB_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar tienda-db desde ECR" \
          --parameters '{"commands":[
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin '$ECR_REGISTRY'",
            "docker pull '$ECR_REGISTRY'/'$IMAGE_NAME':latest",
            "docker stop tienda-db || true",
            "docker rm tienda-db || true",
            "docker run -d --name tienda-db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} '$ECR_REGISTRY'/'$IMAGE_NAME':latest"
          ]}' \
          --output text