name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: [ "main" ]
    paths:
      - "db/**"
  workflow_dispatch: {}

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest
    env:
      # Renombramos para evitar conflictos de variables de entorno
      MI_REGISTRY_URL: 271179226854.dkr.ecr.us-east-1.amazonaws.com
      MI_IMAGE_NAME: tienda-db

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Construir y Empujar imagen
      run: |
        # Depuración: Verificamos si la variable tiene valor antes de dockerizar
        echo "Valor de MI_REGISTRY_URL es: $MI_REGISTRY_URL"
        
        cd db
        docker build -t $MI_IMAGE_NAME .
        
        # Etiquetar y subir usando variables explícitas
        docker tag $MI_IMAGE_NAME:latest $MI_REGISTRY_URL/$MI_IMAGE_NAME:latest
        docker push $MI_REGISTRY_URL/$MI_IMAGE_NAME:latest

    - name: Desplegar DB vía SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_DB_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar tienda-db desde ECR" \
          --parameters '{"commands":[
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin '$MI_REGISTRY_URL'",
            "docker pull '$MI_REGISTRY_URL'/'$MI_IMAGE_NAME':latest",
            "docker stop tienda-db || true",
            "docker rm tienda-db || true",
            "docker run -d --name tienda-db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} '$MI_REGISTRY_URL'/'$MI_IMAGE_NAME':latest"
          ]}' \
          --output text
